function PatientResults(arrivalTimes, startTime, finishTime, waitTime, startHour,doctorAssigned)
  if isempty(arrivalTimes)
    printf("No patients in this zone.\n\n");
  return;
  endif
  printf('\n');
  printf('%-10s%-12s%-12s%-12s%-15s%-12s%-12s\n', ...
         'Patient', 'Arrival', 'Start', ...
         'Finish', 'Service(min)', 'Wait(min)','Doctor');

  for i = 1:length(arrivalTimes)

    serviceTime = finishTime(i) - startTime(i);

    printf('%-10d%-12s%-12s%-12s%-15.2f%-12.2f%-12d\n', ...
           i, ...
           toClockTime(arrivalTimes(i), startHour), ...
           toClockTime(startTime(i), startHour), ...
           toClockTime(finishTime(i), startHour), ...
           serviceTime, ...
           waitTime(i),...
           doctorAssigned(i));

  endfor

  printf('\n\n');

endfunction
